# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(658, 302)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.contentWidgetHolder = QtGui.QWidget(Form)
        self.contentWidgetHolder.setObjectName("contentWidgetHolder")
        self.contentWidgetVerticalLayout = QtGui.QVBoxLayout(self.contentWidgetHolder)
        self.contentWidgetVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.contentWidgetVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.contentWidgetVerticalLayout.setObjectName("contentWidgetVerticalLayout")
        self.verticalLayout.addWidget(self.contentWidgetHolder)
        self.line_3 = QtGui.QFrame(Form)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.widget_2 = QtGui.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtGui.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.appComboBox = QtGui.QComboBox(self.widget_2)
        self.appComboBox.setObjectName("appComboBox")
        self.appComboBox.addItem("")
        self.gridLayout.addWidget(self.appComboBox, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tkTemplateComboBox = QtGui.QComboBox(self.widget_2)
        self.tkTemplateComboBox.setObjectName("tkTemplateComboBox")
        self.tkTemplateComboBox.addItem("")
        self.gridLayout.addWidget(self.tkTemplateComboBox, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.extraTokensWidget = QtGui.QWidget(self.widget_2)
        self.extraTokensWidget.setObjectName("extraTokensWidget")
        self.extraTokensWidgetLayout = QtGui.QGridLayout(self.extraTokensWidget)
        self.extraTokensWidgetLayout.setContentsMargins(0, 0, 0, 0)
        self.extraTokensWidgetLayout.setContentsMargins(0, 0, 0, 0)
        self.extraTokensWidgetLayout.setObjectName("extraTokensWidgetLayout")
        self.gridLayout.addWidget(self.extraTokensWidget, 4, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.widget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.descriptionLabel = QtGui.QLabel(self.widget_2)
        self.descriptionLabel.setText("")
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.gridLayout.addWidget(self.descriptionLabel, 2, 1, 1, 1)
        self.line_4 = QtGui.QFrame(self.widget_2)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 3, 0, 1, 2)
        self.verticalLayout.addWidget(self.widget_2)
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.filePathWidgetGroup = QtGui.QWidget(Form)
        self.filePathWidgetGroup.setObjectName("filePathWidgetGroup")
        self.gridLayout_3 = QtGui.QGridLayout(self.filePathWidgetGroup)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.filePathLineEdit = QtGui.QLineEdit(self.filePathWidgetGroup)
        self.filePathLineEdit.setText("")
        self.filePathLineEdit.setReadOnly(True)
        self.filePathLineEdit.setObjectName("filePathLineEdit")
        self.gridLayout_3.addWidget(self.filePathLineEdit, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.filePathWidgetGroup)
        self.label_5.setStyleSheet("color: rgb(67, 131, 168);\n"
"font: 75 10pt \"Arial\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.filePathWidgetGroup)
        self.label_4.setStyleSheet("color: rgb(67, 131, 168);\n"
"font: 75 10pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.directoryPathCopyButton = QtGui.QPushButton(self.filePathWidgetGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directoryPathCopyButton.sizePolicy().hasHeightForWidth())
        self.directoryPathCopyButton.setSizePolicy(sizePolicy)
        self.directoryPathCopyButton.setMaximumSize(QtCore.QSize(35, 16777215))
        self.directoryPathCopyButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.directoryPathCopyButton.setIcon(icon)
        self.directoryPathCopyButton.setObjectName("directoryPathCopyButton")
        self.gridLayout_3.addWidget(self.directoryPathCopyButton, 1, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.filePathWidgetGroup)
        self.label_6.setStyleSheet("color: rgb(67, 131, 168);\n"
"font: 75 10pt \"Arial\";")
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.fileNameCopyButton = QtGui.QPushButton(self.filePathWidgetGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileNameCopyButton.sizePolicy().hasHeightForWidth())
        self.fileNameCopyButton.setSizePolicy(sizePolicy)
        self.fileNameCopyButton.setMaximumSize(QtCore.QSize(35, 16777215))
        self.fileNameCopyButton.setText("")
        self.fileNameCopyButton.setIcon(icon)
        self.fileNameCopyButton.setObjectName("fileNameCopyButton")
        self.gridLayout_3.addWidget(self.fileNameCopyButton, 0, 4, 1, 1)
        self.createFileButton = QtGui.QPushButton(self.filePathWidgetGroup)
        self.createFileButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/res/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createFileButton.setIcon(icon1)
        self.createFileButton.setObjectName("createFileButton")
        self.gridLayout_3.addWidget(self.createFileButton, 2, 2, 1, 1)
        self.filePathCopyButton = QtGui.QPushButton(self.filePathWidgetGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filePathCopyButton.sizePolicy().hasHeightForWidth())
        self.filePathCopyButton.setSizePolicy(sizePolicy)
        self.filePathCopyButton.setMaximumSize(QtCore.QSize(35, 16777215))
        self.filePathCopyButton.setText("")
        self.filePathCopyButton.setIcon(icon)
        self.filePathCopyButton.setObjectName("filePathCopyButton")
        self.gridLayout_3.addWidget(self.filePathCopyButton, 2, 4, 1, 1)
        self.filePathOpenButton = QtGui.QPushButton(self.filePathWidgetGroup)
        self.filePathOpenButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/res/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filePathOpenButton.setIcon(icon2)
        self.filePathOpenButton.setObjectName("filePathOpenButton")
        self.gridLayout_3.addWidget(self.filePathOpenButton, 2, 3, 1, 1)
        self.directoryPathOpenButton = QtGui.QPushButton(self.filePathWidgetGroup)
        self.directoryPathOpenButton.setText("")
        self.directoryPathOpenButton.setIcon(icon2)
        self.directoryPathOpenButton.setObjectName("directoryPathOpenButton")
        self.gridLayout_3.addWidget(self.directoryPathOpenButton, 1, 3, 1, 1)
        self.dirPathLineEdit = QtGui.QLineEdit(self.filePathWidgetGroup)
        self.dirPathLineEdit.setText("")
        self.dirPathLineEdit.setReadOnly(True)
        self.dirPathLineEdit.setObjectName("dirPathLineEdit")
        self.gridLayout_3.addWidget(self.dirPathLineEdit, 1, 1, 1, 2)
        self.fileNameLineEdit = QtGui.QLineEdit(self.filePathWidgetGroup)
        self.fileNameLineEdit.setText("")
        self.fileNameLineEdit.setReadOnly(True)
        self.fileNameLineEdit.setObjectName("fileNameLineEdit")
        self.gridLayout_3.addWidget(self.fileNameLineEdit, 0, 1, 1, 3)
        self.verticalLayout.addWidget(self.filePathWidgetGroup)
        self.line_5 = QtGui.QFrame(Form)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setStyleSheet("color: rgb(67, 131, 168);\n"
"font: 75 10pt \"Arial\";")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_2 = QtGui.QPushButton(Form)
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setText("")
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.appComboBox.setItemText(0, QtGui.QApplication.translate("Form", "Select Application", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Extra Tokens:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Application:", None, QtGui.QApplication.UnicodeUTF8))
        self.tkTemplateComboBox.setItemText(0, QtGui.QApplication.translate("Form", "Select Template", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Toolkit Template:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Template Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Directory Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "File Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.directoryPathCopyButton.setToolTip(QtGui.QApplication.translate("Form", "Copy Path to Clipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "File Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.fileNameCopyButton.setToolTip(QtGui.QApplication.translate("Form", "Copy Path to Clipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.createFileButton.setToolTip(QtGui.QApplication.translate("Form", "Create File on Disk", None, QtGui.QApplication.UnicodeUTF8))
        self.filePathCopyButton.setToolTip(QtGui.QApplication.translate("Form", "Copy Path to Clipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.filePathOpenButton.setToolTip(QtGui.QApplication.translate("Form", "Open in File Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.directoryPathOpenButton.setToolTip(QtGui.QApplication.translate("Form", "Open in File Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Copy File To File Path", None, QtGui.QApplication.UnicodeUTF8))

from . import resources_rc
